Basline profile association with login
Arsollo/Soen-341-Project pull request #46
Opened 2021-11-11 15:42 UTC by SheriefS

I have updated the Question.py variable email to have association with the email on the profile.html page. This should allow for further integration of actual user data on the profile page.
For additional feature #43

2021-11-11 20:07 UTC, Arsollo requested changes
I think there is something wrong, this commit doesn't contain any changes!

2021-11-11 20:28 UTC, SheriefS commented
It doesn't make any sense, I even tried adding them to a second commit directly on the patch 6.3 branch and they are not there.

2021-11-11 20:40 UTC, SheriefS commented
The files are there now

2021-11-16 17:35 UTC, Arsollo approved these changes

2021-11-16 17:35 UTC, merged